Disabling rmc in KVM script
ocp-power-automation/ocp4-upi-kvm pull request #60
Opened 2020-10-22 11:54 UTC by satwinder0867

@sudeeshjohn

2020-10-27 07:29 UTC, satwinder0867 commented
These changes are made as the RMC container is not reqd for the Libvert cluster as per discussion b/w Archana and Manju.
^ ^@mkumatag

2020-10-27 07:49 UTC, mkumatag requested changes

2020-10-27 07:49 UTC, mkumatag commented on modules/5_install/templates/install_vars.yaml
> +powervm_rmc: false
LGTM

Just add a new line at the end

2020-10-27 07:50 UTC, mkumatag commented
Let's get the review comments from @yussufsh and @Prajyot-Parab as well.

2020-10-30 07:14 UTC, satwinder0867 commented
@yussufsh @Prajyot-Parab 
Extra line is added at the end, plz merge it

2020-10-30 07:19 UTC, mkumatag commented
@satwinder0867 fix the commit author, it says root at the moment,

how to fix - https://stackoverflow.com/questions/25339671/git-uses-root-instead-of-my-username-while-commit-linux

2020-10-30 10:35 UTC, mkumatag commented
If you look at the commit is still says - `root authored and satwinder0867 committed 2 hours ago` seems like still stuck with co-authored,

2020-11-02 11:11 UTC, satwinder0867 commented
@mkumatag @yussufsh 
i made changes again, hope this time its good to merge
let me know if any more changes are reqd.

2020-11-02 11:22 UTC, Prajyot-Parab commented
@satwinder0867 Please refer to the below format, try to sign off your commit properly before pushing `git commit -m <message> -s`

```
<Commit Message>
Signed-off-by: <GH username> <Mail>
```

2020-11-03 09:09 UTC, Prajyot-Parab approved these changes
/lgtm

2020-11-03 09:35 UTC, mkumatag approved these changes
LGTM

2020-11-03 12:46 UTC, yussufsh approved these changes
lgtm

2020-11-03 12:46 UTC, merged